encryptionsalt: v1:1pJ/3O/WvGY=:v1:oqJlz7qaUZ677PLv:5k4WXzQQrbjXhRYPzjrMzR6M8B272g==
config:
  aws:region: ap-northeast-1
  vrc-service-status-panel:cloudflareAccountId: 32cd31ff8a5c721c0583f57a83cb731e
  vrc-service-status-panel:deliveryZoneId: 9e3a1e4d7a8a79af45c16b1e5fcd176c
  vrc-service-status-panel:deliveryHost: vrc-status.oxymoron.link
  vrc-service-status-panel:bucketLocation: apac
  vrc-service-status-panel:youtubeProbeVideoId: "-3opIii0LBU"
  vrc-service-status-panel:boothProbeItemId: "8763171"
  vrc-service-status-panel:ytdlpVersion: 2026.07.04
  vrc-service-status-panel:alertWebhookUrl:
    secure: v1:pHmgTdBtNokpCuxS:T8gNTUyTlxDFFAMUrx/lPBHgPSTfUNZIJG38VlgcxBy4sugVzs4U6ximaIdTg4/Pt6uBRDyBPrbEgTakouPH58E07dOiQW/tYLL2iD486oSPz1F3VzvmIcpZWj4fzTxd6O6VG4XS6UI/zx8QMwidja9/z07ODZz4cfBpsZX1Ks8l0Zmu5qSCfQ2DmIiioWA7ylBplX4BmSClxXHR6hL83BoJCD0TgcCeCagM/TI5lrhYDMz3B8GaNt5ocP7dA1Rkh4g8rDGokrasf0i2RLJUbsyUDCQ7WZvIqm6J5MpOs1S0d1KjPV9Cc3V7nMX4eormetBh9V9C9XJJ0mwLjGNqBC8U
  vrc-service-status-panel:workloadBoundaryName: qazx7412-vrc-service-status-panel-workload-boundary
